version: '3.8'

services:

  server:
    build: .
    container_name: sctrack
    image: sctrack-img
    env_file:
      - .env
    ports:
      - 3030:3030
    volumes:
      - .:/usr/src/app
    # command: air cmd/main.go -b 0.0.0.0

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - server

  # db:
  #  image: postgres:alpine
  #  environment:
  #    - POSTGRES_HOST=${DB_HOST}
  #    - POSTGRES_USER=${DB_USER}
  #    - POSTGRES_PASSWORD=${DB_PASSWORD}
  #    - POSTGRES_DB=${DB_NAME}
  #  ports:
  #    - 5432:5432
  #  volumes:
  #    - postgres-db:/var/lib/postgresql/data

#volumes:
#  postgres-db:

